### ISSUE TITLE
for 0.1.0v release

### ISSUE THREAD

**Issue by oriSomething** [oriSomething/computed#2]
### Todo:
- [x] fix the need for arguments hack for `get` in the `computed`
- [ ] use `WeakMap` for manage observers
- [ ] add `set` functionality in `computed`
- [ ] change `oneWay` name to `computedBy` (maybe `prefer`)
- [ ] create `oneWay` as `Ember.computed.oneWay`
- [ ] better explanation in `README.md`
### Nice to have:
- [ ] computed properties for path (example: `computed('obj.prop.[].anotherProp', ···)`)
